# Generated by Django 2.2.3 on 2019-07-09 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cities', to='rooms.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('postal_code', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/<django.db.models.fields.related.ForeignKey>/')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity', models.SmallIntegerField(choices=[(0, '-'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], default=6)),
                ('room_type', models.SmallIntegerField(choices=[(1, 'Apartment'), (2, 'House'), (3, 'Garden House'), (4, 'Bed and Breakfast'), (5, 'Villa'), (6, 'Caravan'), (50, 'Office')], default=1)),
                ('space', models.SmallIntegerField(choices=[(1, 'Entire Place'), (2, 'Private Room'), (3, 'Shared Room')], default=1)),
                ('bedroom', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1)),
                ('bed_type', models.SmallIntegerField(choices=[(1, 'Private'), (2, 'Shared')], default=1)),
                ('bathroom', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1)),
                ('cancellation', models.SmallIntegerField(choices=[(1, 'Flexible'), (2, 'Semi-flexible'), (3, 'Strict')], default=1)),
                ('min_stay', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89)], default=1)),
                ('max_stay', models.SmallIntegerField(choices=[(0, 'Unlimited'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59)], default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('favorite_counter', models.ImageField(default=0, upload_to='')),
                ('accuracy_rating', models.SmallIntegerField(choices=[(0, 'Not rated'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('location_rating', models.SmallIntegerField(choices=[(0, 'Not rated'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('communication_rating', models.SmallIntegerField(choices=[(0, 'Not rated'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('checkin_rating', models.SmallIntegerField(choices=[(0, 'Not rated'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('clean_rating', models.SmallIntegerField(choices=[(0, 'Not rated'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('value_rating', models.SmallIntegerField(choices=[(0, 'Not rated'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rooms', to='rooms.State')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
