# Generated by Django 2.2.3 on 2019-07-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20190716_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='reserved_dates',
            field=models.TextField(default='', editable=False),
        ),
    ]
