# Generated by Django 2.2.3 on 2019-07-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20190717_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='accuracy_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='checkin_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='clean_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='communication_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='location_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='total_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='value_rating',
            field=models.FloatField(default=0),
        ),
    ]
