# Generated by Django 2.2.3 on 2019-07-31 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_count', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration_time', models.SmallIntegerField(default=2)),
                ('host_about', models.TextField(default='게스트에게 자기 소개와 함께 트립 진행에 있어 나만의 특별함을 알려주세요.')),
                ('program', models.TextField(default='트립을 처음부터 끝까지 실제 진행 순서대로 설명해 주세요.')),
                ('place_info', models.TextField(default='트립에서 방문할 각 장소에 대해 설명하세요.')),
                ('address', models.CharField(blank=True, max_length=250)),
                ('guest_material', models.CharField(blank=True, max_length=250)),
                ('image_1', models.ImageField(blank=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, upload_to='')),
                ('image_4', models.ImageField(blank=True, upload_to='')),
                ('image_5', models.ImageField(blank=True, upload_to='')),
                ('image_6', models.ImageField(blank=True, upload_to='')),
                ('image_7', models.ImageField(blank=True, upload_to='')),
                ('min_age', models.PositiveIntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29)], default=18)),
                ('compatibility', models.CharField(choices=[('YES', '적합하지 않음'), ('NO', '예')], default='YES', max_length=100)),
                ('strength', models.CharField(choices=[('LIGHT', '가벼움'), ('NORMAL', '보통'), ('VEHEMENCE', '격렬함'), ('EXTREME', '익스트림')], default='LIGHT', max_length=100)),
                ('technic', models.CharField(choices=[('BEGINNER', '초급'), ('INTERMEDIATE', '중급'), ('MASTER', '고')], default='BEGINNER', max_length=100)),
                ('additional_contition', models.TextField(default='추가 요건(선택 사항)', max_length=250)),
                ('certification', models.BooleanField(default=False)),
                ('max_guest', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=4)),
                ('price', models.IntegerField(default=30000)),
                ('rating_score', models.FloatField(default=0.0)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.State')),
            ],
            options={
                'ordering': ('-rating_score',),
            },
        ),
        migrations.CreateModel(
            name='TripCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TripSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('capacity', models.IntegerField(default=0)),
                ('now_guest_count', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_trip_schedules', to=settings.AUTH_USER_MODEL)),
                ('trip_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='trips.Trip')),
                ('user_set', models.ManyToManyField(blank=True, related_name='trip_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('rating_score', models.SmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_reviews', to='trips.Reservation')),
                ('trip_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_reviews', to='trips.Trip')),
                ('user_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripProvide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='제공하는 것에 대해 상세하게 적어주세요.')),
                ('provide_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_provides', to='trips.Provide')),
                ('trip_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provides', to='trips.Trip')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.TripCategory'),
        ),
        migrations.CreateModel(
            name='SubTripCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image_1', models.ImageField(blank=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, upload_to='')),
                ('description', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_tripcategory', to='trips.TripCategory')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_tripcategory', to='trips.State')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='trip_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='trips.TripSchedule'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='trip_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='trips.Trip'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL),
        ),
    ]
