# Generated by Django 2.2.3 on 2019-07-31 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripreview',
            old_name='reservation',
            new_name='reservation_set',
        ),
    ]
