# Generated by Django 2.2.3 on 2019-07-31 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20190731_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='trip_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_reservations', to='trips.TripSchedule'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='trip_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_reservations', to='trips.Trip'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
